name = "cloudflare-fullstack"
compatibility_date = "2023-08-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cloudflare_fullstack_db"
database_id = "bd-9731-04052d5b615b" #set the database id here
preview_database_id = "7d84-bd-9731-04052d5b615b"    # this is the local db 
migrations_dir ='migrationsD1'


[[kv_namespaces]]
binding = "KV"
id = "ac5ef8073e3a4sdsdssdsdsdsds"       # remote id
preview_id = "ac5ef8073es3a4esdsdsdsdsd" # local id
